
CREATE TABLE IF NOT EXISTS customer (
    ID                  BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 10001 INCREMENT BY 1 ) NOT NULL,
    FIRST_NAME          VARCHAR(120),
    LAST_NAME           VARCHAR(120),
    EMAIL_ADDRESS       VARCHAR(120),
    LOCATION            VARCHAR(80),
    CONSTRAINT pk_customer PRIMARY KEY (ID),
    CONSTRAINT unique_customer UNIQUE (EMAIL_ADDRESS)
);

CREATE TABLE IF NOT EXISTS product (
    CODE               VARCHAR(16) NOT NULL ,
    PRODUCT_COST       NUMERIC(18,2),
    PRODUCT_STATUS     VARCHAR(10),
    CONSTRAINT pk_product PRIMARY KEY (CODE)
);

CREATE TABLE IF NOT EXISTS customer_transaction (
    ID                     BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 10001 INCREMENT BY 1 )  NOT NULL,
    TRANSACTION_DATETIME   TIMESTAMP NOT NULL,
    CUSTOMER_ID            BIGINT NOT NULL,
    PRODUCT_QUANTITY       INTEGER NOT NULL DEFAULT 0,
    PRODUCT_CODE           VARCHAR(16) NOT NULL,
    CONSTRAINT pk_customer_transaction PRIMARY KEY (ID),
    CONSTRAINT fk_customer_transaction_cust FOREIGN KEY (CUSTOMER_ID) REFERENCES  customer (ID) ON DELETE  CASCADE,
    CONSTRAINT fk_customer_transaction_prod FOREIGN KEY (PRODUCT_CODE) REFERENCES  product (CODE) ON DELETE  CASCADE
);
